version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "color-expert"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qdvy08gcc0q0"
s3_prefix = "color-expert"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TopicNameParameter=\"\""
